// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grefeadcdigdutrqwwmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyZWZlYWRjZGlnZHV0cnF3d21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTY2MDYsImV4cCI6MjA2NTQzMjYwNn0.1G5y6IkW_agVGoVS2O2fEgP6UEaVR6y3tJ2Bch4wYf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);